### ISSUE TITLE
Redirect fIles missing

### ISSUE THREAD

**Issue by vitormalencar** [rodrigoronin/ronin-pokedex#2]
when using netlify and CRA apps with react-router you need to add a redirect file to handle redirect on root path
 
![2020-07-16 15 37 26](https://user-images.githubusercontent.com/7741167/87677664-52f5cf00-c77a-11ea-8496-9719d8b4cff6.gif)

**Comment by rodrigoronin** [comment]
Thank you for the info @vitormalencar. I will fix that on next update.
